NIMBLE_INCLUDE += \
	$(NIMBLE_ROOT)/ext/tinycrypt/include \

NIMBLE_SRC += \
	$(NIMBLE_ROOT)/ext/tinycrypt/src/aes_decrypt.c \
	$(NIMBLE_ROOT)/ext/tinycrypt/src/aes_encrypt.c \
	$(NIMBLE_ROOT)/ext/tinycrypt/src/cmac_mode.c \
	$(NIMBLE_ROOT)/ext/tinycrypt/src/ecc.c \
	$(NIMBLE_ROOT)/ext/tinycrypt/src/ecc_dh.c \
	$(NIMBLE_ROOT)/ext/tinycrypt/src/utils.c \
