NIMBLE_INCLUDE += \
	$(NIMBLE_ROOT)/nimble/host/mesh/include \

NIMBLE_SRC += \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/access.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/adv.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/beacon.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/cfg_cli.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/cfg_srv.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/crypto.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/friend.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/glue.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/health_cli.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/health_srv.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/light_model.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/lpn.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/mesh.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/model_cli.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/model_srv.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/net.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/prov.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/proxy.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/shell.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/testing.c \
	$(NIMBLE_ROOT)/nimble/host/mesh/src/transport.c \
