BLE_EDDYSTONE: 1
BLE_EXT_ADV: 1
BLE_EXT_ADV_MAX_SIZE: 1650
BLE_HS_DEBUG: 1
BLE_L2CAP_COC_MAX_NUM: 5
BLE_L2CAP_ENHANCED_COC: 1

BLE_MAX_CONNECTIONS: 5
BLE_MONITOR_RTT: 1
BLE_MULTI_ADV_INSTANCES: 5
BLE_PERIODIC_ADV: 1
BLE_MAX_PERIODIC_SYNCS: 5
BLE_PERIODIC_ADV_SYNC_TRANSFER: 1
BLE_SM_BONDING: 1
BLE_SM_LEGACY: 1
BLE_SM_SC: 1
BLE_STORE_MAX_BONDS: 5
BLE_VERSION: 52

BLE_LL_CFG_FEAT_LE_2M_PHY: 1
BLE_LL_CFG_FEAT_LE_CODED_PHY: 1
BLE_LL_CFG_FEAT_LL_PRIVACY: 1
BLE_LL_CONN_INIT_MAX_TX_BYTES: 251
BLE_LL_DTM: 1
BLE_LL_DTM_EXTENSIONS: 1
